[uwsgi]
chdir = /badgr_server
module = wsgi:application
master = true
processes = 4
threads = 2

http = :8000  # remplacer socket par HTTP pour debug initial
vacuum = true
enable-threads = true
thunder-lock = true
die-on-term = true

uid = www-data
gid = www-data

logto = /var/log/uwsgi/uwsgi.log
